require("core.cfg_plugins.colorscheme")
require("core.cfg_plugins.lualine")
require("core.cfg_plugins.treesitter")
require("core.cfg_plugins.minifiles")
require("core.cfg_plugins.snip")
require("core.cfg_plugins.lsp")
require("core.cfg_plugins.whichkey")
-- require("core.cfg_plugins.codecompanion")
-- require("core.cfg_plugins.codeium")
require("core.cfg_plugins.completions")
require("core.cfg_plugins.devicons")
require("core.cfg_plugins.fzf")
require("core.cfg_plugins.comment")
require("core.cfg_plugins.colorhls")
